# Traefik v3.0 Configuration File
# =================================
# Updated for internal use behind Caddy

# Global Configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and Dashboard Configuration
api:
  dashboard: true
  debug: false

# Entrypoints Configuration
entryPoints:
  web:
    address: ":80" # Internal port for Caddy to connect

  websecure:
    address: ":443" # Internal HTTPS port (optional)

# Providers Configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "docker-compose_netsocs-network" # Updated with project prefix
    watch: true

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Logging Configuration
log:
  level: INFO
  format: json

# Access Logs
accessLog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop

# Metrics Configuration (optional)
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# Ping endpoint for health checks
ping:
  entryPoint: web

# Health check endpoint
healthcheck:
  interval: "10s"
  timeout: "5s"

experimental:
  plugins:
    keycloakopenid:
      moduleName: "github.com/Netsocs-Team/keycloakopenid"
      version: "v1.0.4"
    sec:
      moduleName: "github.com/Netsocs-Team/traefik-owasp-security"
      version: "v1.3.8"
