# Traefik v3.0 Configuration File
# =================================

# Global Configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and Dashboard Configuration
api:
  dashboard: true
  debug: false

# Entrypoints Configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

# Providers Configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: netsocs-network
    watch: true

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Logging Configuration
log:
  level: INFO
  format: json

# Access Logs
accessLog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop

# Metrics Configuration (optional)
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# Ping endpoint for health checks
ping:
  entryPoint: web

# Health check endpoint
healthcheck:
  interval: "10s"
  timeout: "5s"
