# Traefik Dynamic Configuration - Middleware
# =========================================

# CORS Middleware Example
http:
  middlewares:
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - Authorization
          - Content-Type
          - X-Requested-With
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 86400
        addVaryHeader: true

    # Rate Limiting Middleware Example
    rate-limit:
      rateLimit:
        average: 100
        burst: 50

    # Security Headers Middleware Example
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          Server: ""

    # Basic Auth Middleware Example (uncomment and configure as needed)
    # basic-auth:
    #   basicAuth:
    #     users:
    #       - "admin:$2y$10$..."
    #     removeHeader: true

    # IP Whitelist Middleware Example (uncomment and configure as needed)
    # ip-whitelist:
    #   ipWhiteList:
    #     sourceRange:
    #       - "10.0.0.0/8"
    #       - "172.16.0.0/12"
    #       - "192.168.0.0/16"
